### ISSUE TITLE
Fetch RequestInit method parameter issue

### ISSUE THREAD

**Issue by TomiS** [TheSpyder/rescript-webapi#128]
Hey, I'm not sure if this is a ReScript 11 thing or something else, but in order to make fetching work properly, I needed to change [this line](https://github.com/TheSpyder/rescript-webapi/blob/3a973a103b239a945db9457c99eee6d21d942c34/src/Webapi/Webapi__Fetch.res#L312) and [this line](https://github.com/TheSpyder/rescript-webapi/blob/3a973a103b239a945db9457c99eee6d21d942c34/src/Webapi/Webapi__Fetch.res#L342) in such way that neither have underscore as prefix

e.g.
```
~_method: string=?,
```
=>
```
~method: string=?,
```

The current implementation does not work when using `DELETE` as method (at least). It causes an error
`TypeError: Failed to construct 'Request': Request with GET/HEAD method cannot have body.`

**Comment by TheSpyder** [comment]
Yes https://github.com/rescript-lang/rescript-compiler/pull/6354 removed the `_` mangling. I'll try to find some way to fix this without breaking ReScript 10 compatibility. It would be a shame to need a breaking version change just for v11 support.

I am long overdue for a 1.0 release, though.  So if I do need to break it I'll keep v1 for rescript 10 and make a v2 branch for rescript 11.

**Comment by TheSpyder** [comment]
Other locations:
https://github.com/tinymce/rescript-webapi/blob/5219ef22571c7e79ac221d049c1ad19546270c99/src/Webapi/Webapi__File.res#L15
https://github.com/tinymce/rescript-webapi/blob/5219ef22571c7e79ac221d049c1ad19546270c99/src/Webapi/Webapi__Blob.res#L30

And the tests for both

**Comment by TomiS** [comment]
Sounds good. Thanks for clarifying.

**Comment by TheSpyder** [comment]
I didn't see your edit. That's... probably something I should've reported to the compiler team. Hmm.
