### ISSUE TITLE
`toggleForced` should be able to send `false`

### ISSUE THREAD

**Issue by jcuenod** [TheSpyder/rescript-webapi#134]
It seems as though the `toggleForced` method only forces toggling `on`. Shouldn't this method expect a `bool`?

https://github.com/TheSpyder/rescript-webapi/blob/7f2cf0a00bada710126d7f5d4968ae54b19b0471/src/Webapi/Dom/Webapi__Dom__DomTokenList.res#L17

**Comment by TheSpyder** [comment]
Yes, it probably should.

Most of this code is quite old, the conversion to ReScript was mostly automated. Feel free to submit a PR for any weird errors like this you come across!
